In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
hex_grid = gpd.read_file('/Users/pedrickr/Documents/ADR/Connectivity/Hex_Grid_250m_UK.gpkg')
hex_grid

,id,left,top,right,bottom,row_index,col_index,geometry
0,2780,-116.192800,525551.625,172.482335,525301.625,2779,0,"MULTIPOLYGON (((-68.882 525345.103, -61.583 52..."
1,2781,-116.192800,525301.625,172.482335,525051.625,2780,0,"MULTIPOLYGON (((114.605 525275.518, 106.004 52..."
2,7639,100.313551,525676.625,388.988686,525426.625,2778,1,"MULTIPOLYGON (((122.793 525517.432, 130.878 52..."
3,7640,100.313551,525426.625,388.988686,525176.625,2779,1,"MULTIPOLYGON (((348.428 525241.845, 338.736 52..."
4,7641,100.313551,525176.625,388.988686,524926.625,2780,1,"MULTIPOLYGON (((328.605 524951.639, 327.668 52..."
...,...,...,...,...,...,...,...,...
4572242,14719785,655465.037865,294301.625,655753.712999,294051.625,3704,3028,"MULTIPOLYGON (((655485.26 294199.04, 655484.2 ..."
4572243,14719786,655465.037865,294051.625,655753.712999,293801.625,3705,3028,"MULTIPOLYGON (((655515.04 294000.53, 655516.95..."
4572244,14719787,655465.037865,293801.625,655753.712999,293551.625,3706,3028,"MULTIPOLYGON (((655580.65 293799.28, 655589.5 ..."
4572245,14719788,655465.037865,293551.625,655753.712999,293301.625,3707,3028,"MULTIPOLYGON (((655549.82 293547.42, 655548.53..."
4572246,14719789,655465.037865,293301.625,655753.712999,293051.625,3708,3028,"MULTIPOLYGON (((655538.5 293292.65, 655538 293..."

In [3]:
len(hex_grid)

4572247

In [4]:
hex_grid.to_parquet("/Users/pedrickr/Documents/ADR/Connectivity/hexes.parquet")

In [5]:
gdf = gpd.read_parquet(
    "/Users/pedrickr/Documents/ADR/Connectivity/hexes.parquet"
)

In [6]:
gdf.head()

,id,left,top,right,bottom,row_index,col_index,geometry
0,2780,-116.192800,525551.625,172.482335,525301.625,2779,0,"MULTIPOLYGON (((-68.882 525345.103, -61.583 52..."
1,2781,-116.192800,525301.625,172.482335,525051.625,2780,0,"MULTIPOLYGON (((114.605 525275.518, 106.004 52..."
2,7639,100.313551,525676.625,388.988686,525426.625,2778,1,"MULTIPOLYGON (((122.793 525517.432, 130.878 52..."
3,7640,100.313551,525426.625,388.988686,525176.625,2779,1,"MULTIPOLYGON (((348.428 525241.845, 338.736 52..."
4,7641,100.313551,525176.625,388.988686,524926.625,2780,1,"MULTIPOLYGON (((328.605 524951.639, 327.668 52..."

In [7]:
gdf["id"].is_unique

True

In [8]:
gdf["id"].nunique()

4572247

In [9]:
print(gdf["id"].min())
print(gdf["id"].max())
print(gdf["id"].nunique())

2780
14719789
4572247

In [10]:
hex_grid = hex_grid.set_index("id")

In [11]:
ofcom_pc = gpd.read_file('/Users/pedrickr/Documents/ADR/Connectivity/gdf_merged_ofcom_pc_coverage_202507.gpkg')
ofcom_pc.head()

,PCD7,PCD8,PCDS,DOINTR,DOTERM,CTY25CD,CED25CD,LAD25CD,WD25CD,PARNCP25CD,...,UFBB availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,Gigabit availability (% premises),% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,geometry
0,AB101AF,AB10 1AF,AB10 1AF,199606,None,S99999999,S99999999,S12000033,S13002842,S99999999,...,100.0,0.0,0.0,0.0,0.0,100.0,0.0,100.0,0.0,POINT (394235 806529)
1,AB101AG,AB10 1AG,AB10 1AG,199606,None,S99999999,S99999999,S12000033,S13002842,S99999999,...,100.0,0.0,0.0,0.0,0.0,100.0,0.0,100.0,0.0,POINT (394230 806469)
2,AB101AH,AB10 1AH,AB10 1AH,199606,None,S99999999,S99999999,S12000033,S13002842,S99999999,...,100.0,0.0,0.0,0.0,0.0,100.0,0.0,100.0,0.0,POINT (394235 806529)
3,AB101AL,AB10 1AL,AB10 1AL,199606,None,S99999999,S99999999,S12000033,S13002842,S99999999,...,33.3,0.0,0.0,0.0,0.0,33.3,0.0,100.0,0.0,POINT (394333 806529)
4,AB101AN,AB10 1AN,AB10 1AN,199606,None,S99999999,S99999999,S12000033,S13002842,S99999999,...,80.0,0.0,0.0,0.0,0.0,80.0,0.0,100.0,0.0,POINT (394367 806541)

In [12]:
ofcom_pc.columns

Index(['PCD7', 'PCD8', 'PCDS', 'DOINTR', 'DOTERM', 'CTY25CD', 'CED25CD',
       'LAD25CD', 'WD25CD', 'PARNCP25CD', 'USRTYPIND', 'EAST1M', 'NORTH1M',
       'GRIDIND', 'HLTH19CD', 'NHSER24CD', 'CTRY25CD', 'RGN25CD', 'SSR95CD',
       'PCON24CD', 'EER20CD', 'EDUC23CD', 'TTWA15CD', 'PCO19CD', 'ITL25CD',
       'WDSTL05CD', 'OA01CD', 'WDCAS03CD', 'NPARK16CD', 'LSOA01CD', 'MSOA01CD',
       'RUC01IND', 'OAC01IND', 'OA11CD', 'LSOA11CD', 'MSOA11CD', 'WZ11CD',
       'SICBL24CD', 'BUA24CD', 'RUC11IND', 'OAC11IND', 'LAT', 'LONG',
       'LEP21CD1', 'LEP21CD2', 'PFA23CD', 'IMD20IND', 'CAL24CD', 'ICB23CD',
       'OA21CD', 'LSOA21CD', 'MSOA21CD', 'RUC21IND', 'F_matched_characters',
       'F_matched_parts___part', 'F_matched_parts___startIndex', 'postcode',
       'postcode_space', 'postcode area',
       '% of premises with 30<300Mbit/s download speed',
       '% of premises with >=300Mbit/s download speed',
       '% of premises with 0<2Mbit/s download speed',
       '% of premises with 2<5Mbit/s download speed',
       '% of premises with 5<10Mbit/s download speed',
       '% of premises with 10<30Mbit/s download speed',
       'SFBB availability (% premises)',
       'UFBB (100Mbit/s) availability (% premises)',
       'UFBB availability (% premises)',
       '% of premises unable to receive 2Mbit/s',
       '% of premises unable to receive 5Mbit/s',
       '% of premises unable to receive 10Mbit/s',
       '% of premises unable to receive 30Mbit/s',
       'Gigabit availability (% premises)', '% of premises below the USO',
       '% of premises with NGA',
       '% of premises able to receive decent broadband from FWA', 'geometry'],
      dtype='str')

In [15]:

# --------------------------
# 1. Select only fields needed
# --------------------------

keep_cols = [
    "postcode",
    "Gigabit availability (% premises)",
    "% of premises unable to receive 30Mbit/s",
    "% of premises below the USO",
    "geometry"
]

ofcom_map = ofcom_pc[keep_cols].copy()

# --------------------------
# 2. Create positive measures
# --------------------------

ofcom_map["Access to >=30Mbps (% premises)"] = (
    100 - ofcom_map["% of premises unable to receive 30Mbit/s"]
)

ofcom_map["Above USO (% premises)"] = (
    100 - ofcom_map["% of premises below the USO"]
)

# --------------------------
# 3. Spatial join
# --------------------------

# assuming:
# hex_grid = hex polygons
# ofcom_map = postcode centroids

joined = gpd.sjoin(
    ofcom_map,
    hex_grid,
    how="left",
    predicate="within"
)

# --------------------------
# 4. Aggregate to one hex
# --------------------------

hex_metrics = (
    joined
    .groupby("id")
    .agg(
        {
            "Gigabit availability (% premises)": "mean",
            "Access to >=30Mbps (% premises)": "mean",
            "Above USO (% premises)": "mean",
            "postcode": "count"
        }
    )
    .rename(
        columns={
            "postcode": "postcode_count"
        }
    )
    .reset_index()
)

# --------------------------
# 5. Join back to geometry
# --------------------------

hex_broadband = (
    hex_grid
    .reset_index()
    .merge(
        hex_metrics,
        on="id",
        how="left"
    )
)

# back to GeoDataFrame
hex_broadband = gpd.GeoDataFrame(
    hex_broadband,
    geometry="geometry",
    crs=hex_grid.crs
)

# --------------------------
# 6. Save for future use
# --------------------------

hex_broadband.to_parquet(
    "uk_hex_broadband_2025.parquet"
)

In [16]:
hex_broadband.head()

,id,left,top,right,bottom,row_index,col_index,geometry,Gigabit availability (% premises),Access to >=30Mbps (% premises),Above USO (% premises),postcode_count
0,2780,-116.192800,525551.625,172.482335,525301.625,2779,0,"MULTIPOLYGON (((-68.882 525345.103, -61.583 52...",NaN,NaN,NaN,NaN
1,2781,-116.192800,525301.625,172.482335,525051.625,2780,0,"MULTIPOLYGON (((114.605 525275.518, 106.004 52...",NaN,NaN,NaN,NaN
2,7639,100.313551,525676.625,388.988686,525426.625,2778,1,"MULTIPOLYGON (((122.793 525517.432, 130.878 52...",NaN,NaN,NaN,NaN
3,7640,100.313551,525426.625,388.988686,525176.625,2779,1,"MULTIPOLYGON (((348.428 525241.845, 338.736 52...",NaN,NaN,NaN,NaN
4,7641,100.313551,525176.625,388.988686,524926.625,2780,1,"MULTIPOLYGON (((328.605 524951.639, 327.668 52...",NaN,NaN,NaN,NaN

In [17]:
hex_broadband["postcode_count"].describe()

count    536325.000000
mean          3.214763
std           3.519162
min           1.000000
25%           1.000000
50%           2.000000
75%           4.000000
max         224.000000
Name: postcode_count, dtype: float64

In [18]:
hex_broadband = hex_broadband[
    hex_broadband["postcode_count"].notna()
]

In [19]:
len(hex_broadband)

536325

In [20]:
hex_broadband.columns

Index(['id', 'left', 'top', 'right', 'bottom', 'row_index', 'col_index',
       'geometry', 'Gigabit availability (% premises)',
       'Access to >=30Mbps (% premises)', 'Above USO (% premises)',
       'postcode_count'],
      dtype='str')

In [22]:
hex_web = hex_broadband[
    [
        "id",
        "Gigabit availability (% premises)",
        "Access to >=30Mbps (% premises)",
        "Above USO (% premises)",
        "postcode_count",
        "geometry"
    ]
].copy()

In [23]:
hex_web.to_parquet(
    "uk_connectivity_hexes_2025.parquet"
)

In [24]:
len(hex_web)

536325

In [25]:
hex_web.memory_usage(deep=True).sum() / 1024**2

np.float64(28.642845153808594)

hex_web.head()
hex_web.describe()

In [27]:
hex_web[
    [
        "Gigabit availability (% premises)",
        "Access to >=30Mbps (% premises)",
        "Above USO (% premises)"
    ]
].describe()

,Gigabit availability (% premises),Access to >=30Mbps (% premises),Above USO (% premises)
count,536325.000000,536325.000000,536325.000000
mean,67.556660,86.993806,98.851895
std,41.873412,30.293289,8.575822
min,0.000000,0.000000,0.000000
25%,16.650000,100.000000,100.000000
50%,95.300000,100.000000,100.000000
75%,100.000000,100.000000,100.000000
max,100.000000,100.000000,100.000000

In [31]:
hex_web = hex_web.to_crs(4326)

In [32]:
hex_web.to_file(
    "/Users/pedrickr/Documents/ADR/Connectivity/uk_connectivity_hex_2025.geojson",
    driver="GeoJSON"
)

In [33]:
import os

os.path.getsize(
    "/Users/pedrickr/Documents/ADR/Connectivity/uk_connectivity_hex_2025.geojson"
) / 1024**2

305.634464263916

In [35]:
hex_web.total_bounds

array([-8.16506842, 49.8935454 ,  1.76370538, 60.80240174])

In [30]:
tippecanoe \
  -o connectivity.mbtiles \
  -zg \
  --drop-densest-as-needed \
  uk_connectivity_hex_2025.geojson

SyntaxError: invalid syntax (1740281734.py, line 2)